Repository algobot76/surabaya, pull requests merged in 2020-06, with the labels that each got.

#9 Fix package name
  src/main/java/com/github/algobot76/surabaya/SurabayaApplication.java
  src/test/java/com/github/algobot76/surabaya/SurabayaApplicationTests.java
Labels: bug

#12 some assets (can be changed later)
  client/src/assets/icons/Object multiples.png
  client/src/assets/icons/boat left.png
  client/src/assets/icons/boat right.png
  client/src/assets/icons/bool array.png
  client/src/assets/icons/boolean Tree.png
  client/src/assets/icons/constructor volcano.png
  client/src/assets/icons/int lake.png
  client/src/assets/icons/int multiples.png
  client/src/assets/icons/method factory.png
  client/src/assets/icons/object rock.png
  client/src/assets/icons/string multiples.png
  client/src/assets/islands/island1.png
  client/src/assets/islands/island2.png
  client/src/assets/islands/island3.png
  client/src/assets/islands/island4.png
  client/src/assets/islands/island5.png
Labels: enhancement

#10 Finalize data structure
  README.md
Labels: documentation

#13 Add mock response
  pom.xml
  src/main/java/com/github/algobot76/surabaya/controller/AnalysisController.java
  src/main/java/com/github/algobot76/surabaya/util/Constructor.java
  src/main/java/com/github/algobot76/surabaya/util/Field.java
  src/main/java/com/github/algobot76/surabaya/util/Klass.java
  src/main/java/com/github/algobot76/surabaya/util/Method.java
  src/main/java/com/github/algobot76/surabaya/util/Package.java
  src/main/java/com/github/algobot76/surabaya/util/Parameter.java
  src/main/java/com/github/algobot76/surabaya/util/Project.java
Labels: enhancement

#17 Add icon tooltips and island component
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.module.css
  client/src/assets/icons/deciduous.png
  client/src/assets/icons/deciduousMultiples.png
  client/src/assets/icons/evergreen.png
  client/src/assets/icons/evergreenMultiples.png
  client/src/assets/icons/factory.png
  client/src/assets/icons/pond.png
  client/src/assets/icons/pondMultiples.png
  client/src/assets/icons/rock.png
  client/src/assets/icons/rockMultiples.png
  client/src/assets/icons/volcano.png
  client/src/components/IconTooltip/index.tsx
  client/src/components/IconTooltip/styles.module.css
  client/src/components/Island/index.tsx
  client/src/react-app-env.d.ts
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement

#28 AccessModifier enum
  src/main/java/com/github/algobot76/surabaya/controller/AnalysisController.java
  src/main/java/com/github/algobot76/surabaya/util/AccessModifier.java
  src/main/java/com/github/algobot76/surabaya/util/Class.java
  src/main/java/com/github/algobot76/surabaya/util/Constructor.java
  src/main/java/com/github/algobot76/surabaya/util/Field.java
  src/main/java/com/github/algobot76/surabaya/util/Method.java
  src/main/java/com/github/algobot76/surabaya/util/Package.java
Labels: enhancement

#35 Add static analysis for a single file
  src/main/java/com/github/algobot76/surabaya/SurabayaApplication.java
  src/main/java/com/github/algobot76/surabaya/controller/AnalysisController.java
  src/main/java/com/github/algobot76/surabaya/util/AccessModifier.java
  src/main/java/com/github/algobot76/surabaya/util/Analyzer.java
  src/main/java/com/github/algobot76/surabaya/util/Class.java
  src/main/java/com/github/algobot76/surabaya/util/Constructor.java
  src/main/java/com/github/algobot76/surabaya/util/Field.java
  src/main/java/com/github/algobot76/surabaya/util/File.java
  src/main/java/com/github/algobot76/surabaya/util/Method.java
  src/main/java/com/github/algobot76/surabaya/util/Package.java
  src/main/java/com/github/algobot76/surabaya/util/Project.java
  src/main/java/com/github/algobot76/surabaya/util/StaticAnalysisVisitor.java
  src/main/resources/testJavaProject/input.tvar
  src/main/resources/testJavaProject/out/production/tinyVars/ast/DEC.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/EXP.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/NAME.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/NUMBER.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/PRINT.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/PROGRAM.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/SET.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/STATEMENT.class
  src/main/resources/testJavaProject/out/production/tinyVars/libs/Node.class
  src/main/resources/testJavaProject/out/production/tinyVars/libs/Tokenizer.class
  src/main/resources/testJavaProject/out/production/tinyVars/ui/Main.class
  src/main/resources/testJavaProject/src/.DS_Store
  src/main/resources/testJavaProject/src/ast/DEC.java
  src/main/resources/testJavaProject/src/ast/EXP.java
  src/main/resources/testJavaProject/src/ast/NAME.java
  src/main/resources/testJavaProject/src/ast/NUMBER.java
  src/main/resources/testJavaProject/src/ast/PRINT.java
  src/main/resources/testJavaProject/src/ast/PROGRAM.java
  src/main/resources/testJavaProject/src/ast/SET.java
  src/main/resources/testJavaProject/src/ast/STATEMENT.java
  src/main/resources/testJavaProject/src/libs/Node.java
  src/main/resources/testJavaProject/src/libs/Tokenizer.java
  src/main/resources/testJavaProject/src/ui/Main.java
Labels: enhancement

#34 new island images so they fit better
  client/src/assets/islands/island1.png
  client/src/assets/islands/island2.png
  client/src/assets/islands/island3.png
  client/src/assets/islands/island4.png
  client/src/assets/islands/island5.png
  client/src/components/Island/index.tsx
Labels: enhancement

#46 File upload
  .gitignore
  src/main/java/com/github/algobot76/surabaya/SurabayaApplication.java
  src/main/java/com/github/algobot76/surabaya/controller/FileUploadController.java
  src/main/java/com/github/algobot76/surabaya/service/storage/FileSystemStorageService.java
  src/main/java/com/github/algobot76/surabaya/service/storage/StorageException.java
  src/main/java/com/github/algobot76/surabaya/service/storage/StorageFileNotFoundException.java
  src/main/java/com/github/algobot76/surabaya/service/storage/StorageProperties.java
  src/main/java/com/github/algobot76/surabaya/service/storage/StorageService.java
Labels: enhancement

#51 Clump classes together on island
  client/package-lock.json
  client/package.json
  client/src/components/ClassClusters/index.tsx
  client/src/components/IconTooltip/styles.module.css
  client/src/components/Island/index.tsx
  client/src/components/Island/styles.module.css
  client/src/components/TooltipSquare/index.tsx
  client/yarn.lock
Labels: enhancement

#48 Allow imports
  client/src/App.js
  client/src/App.module.css
  client/src/components/ImportPanel/index.tsx
Labels: enhancement

#54 Class flags
  client/src/App.js
  client/src/components/ClassClusters/index.tsx
  client/src/components/ColoredFlag/index.tsx
  client/src/components/IconTooltip/index.tsx
  client/src/components/Island/index.tsx
  client/src/components/TooltipSquare/index.tsx
  client/src/mockFile.json
  client/src/util/constants.js
  client/src/util/helpers.js
Labels: enhancement

#57 Connect backend and frontend
  client/package.json
  client/src/components/ImportPanel/index.tsx
  client/yarn.lock
  src/main/java/com/github/algobot76/surabaya/config/WebConfig.java
Labels: enhancement

#52 Finish static analysis
  .gitignore
  src/main/java/com/github/algobot76/surabaya/SurabayaApplication.java
  src/main/java/com/github/algobot76/surabaya/controller/AnalysisController.java
  src/main/java/com/github/algobot76/surabaya/util/Analyzer.java
  src/main/java/com/github/algobot76/surabaya/util/File.java
  src/main/java/com/github/algobot76/surabaya/util/FileUnzipper.java
  src/main/java/com/github/algobot76/surabaya/util/Package.java
  src/main/java/com/github/algobot76/surabaya/util/Project.java
  src/main/java/com/github/algobot76/surabaya/util/StaticAnalysisVisitor.java
  src/main/resources/test.zip
Labels: enhancement

#61 Update analysis endpoint
  .gitignore
  src/main/java/com/github/algobot76/surabaya/SurabayaApplication.java
  src/main/java/com/github/algobot76/surabaya/controller/AnalysisController.java
  src/main/java/com/github/algobot76/surabaya/service/storage/FileSystemStorageService.java
  src/main/java/com/github/algobot76/surabaya/util/AccessModifier.java
  src/main/java/com/github/algobot76/surabaya/util/Analyzer.java
  src/main/java/com/github/algobot76/surabaya/util/FileUnzipper.java
  src/main/java/com/github/algobot76/surabaya/util/StaticAnalysisVisitor.java
  src/main/resources/test.zip
  src/main/resources/testJavaProject/input.tvar
  src/main/resources/testJavaProject/out/production/tinyVars/ast/DEC.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/EXP.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/NAME.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/NUMBER.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/PRINT.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/PROGRAM.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/SET.class
  src/main/resources/testJavaProject/out/production/tinyVars/ast/STATEMENT.class
  src/main/resources/testJavaProject/out/production/tinyVars/libs/Node.class
  src/main/resources/testJavaProject/out/production/tinyVars/libs/Tokenizer.class
  src/main/resources/testJavaProject/out/production/tinyVars/ui/Main.class
  src/main/resources/testJavaProject/src/.DS_Store
  src/main/resources/testJavaProject/src/ast/DEC.java
  src/main/resources/testJavaProject/src/ast/EXP.java
  src/main/resources/testJavaProject/src/ast/NAME.java
  src/main/resources/testJavaProject/src/ast/NUMBER.java
  src/main/resources/testJavaProject/src/ast/PRINT.java
  src/main/resources/testJavaProject/src/ast/PROGRAM.java
  src/main/resources/testJavaProject/src/ast/SET.java
  src/main/resources/testJavaProject/src/ast/STATEMENT.java
  src/main/resources/testJavaProject/src/libs/Node.java
  src/main/resources/testJavaProject/src/libs/Tokenizer.java
  src/main/resources/testJavaProject/src/ui/Main.java
Labels: enhancement

#62 Add file upload notification
  client/src/components/ImportPanel/index.tsx
Labels: enhancement

#64 Access modifier fences
  client/src/assets/Fences/stoneFence.png
  client/src/assets/Fences/woodenFence.png
  client/src/components/ClassClusters/index.tsx
  client/src/components/ColoredFlag/index.tsx
  client/src/components/IconTooltip/index.tsx
  client/src/components/Island/index.tsx
  client/src/components/TooltipSquare/index.tsx
  client/src/util/constants.js
  client/src/util/helpers.js
Labels: enhancement

#67 Remove mock data
  client/src/App.js
  client/src/components/ImportPanel/index.tsx
  client/src/mockFile.json
Labels: enhancement

#68 Remove .history
  .history/client/public/index_20200605185206.html
  .history/client/src/App.module_20200605185222.css
  .history/client/src/App.module_20200605185248.css
  .history/client/src/App_20200605185107.js
  .history/client/src/App_20200605185117.js
Labels: enhancement

#74 Remove unnecessary maven plugins
  pom.xml
Labels: enhancement

#72 Add basic analyzer tests
  src/main/java/com/github/algobot76/surabaya/util/Analyzer.java
  src/main/java/com/github/algobot76/surabaya/util/Class.java
  src/main/java/com/github/algobot76/surabaya/util/Constructor.java
  src/main/java/com/github/algobot76/surabaya/util/Field.java
  src/main/java/com/github/algobot76/surabaya/util/File.java
  src/main/java/com/github/algobot76/surabaya/util/FileUnzipper.java
  src/main/java/com/github/algobot76/surabaya/util/Method.java
  src/main/java/com/github/algobot76/surabaya/util/Package.java
  src/main/java/com/github/algobot76/surabaya/util/Parameter.java
  src/main/java/com/github/algobot76/surabaya/util/Project.java
  src/test/java/com/github/algobot76/surabaya/util/AnalyzerTests.java
  src/test/resources/SampleJavaProjects/abstractClass.zip
  src/test/resources/SampleJavaProjects/complexZip.zip
  src/test/resources/SampleJavaProjects/interface.zip
  src/test/resources/SampleJavaProjects/multipleClasses.zip
  src/test/resources/SampleJavaProjects/noSrc.zip
  src/test/resources/SampleJavaProjects/simpleZip.zip
  src/test/resources/SampleJavaProjects/test.java
  src/test/testJavaProject/input.tvar
  src/test/testJavaProject/out/production/tinyVars/ast/DEC.class
  src/test/testJavaProject/out/production/tinyVars/ast/EXP.class
  src/test/testJavaProject/out/production/tinyVars/ast/NAME.class
  src/test/testJavaProject/out/production/tinyVars/ast/NUMBER.class
  src/test/testJavaProject/out/production/tinyVars/ast/PRINT.class
  src/test/testJavaProject/out/production/tinyVars/ast/PROGRAM.class
  src/test/testJavaProject/out/production/tinyVars/ast/SET.class
  src/test/testJavaProject/out/production/tinyVars/ast/STATEMENT.class
  src/test/testJavaProject/out/production/tinyVars/libs/Node.class
  src/test/testJavaProject/out/production/tinyVars/libs/Tokenizer.class
  src/test/testJavaProject/out/production/tinyVars/ui/Main.class
  src/test/testJavaProject/src/.DS_Store
  src/test/testJavaProject/src/ast/EXP.java
  src/test/testJavaProject/src/ast/NAME.java
  src/test/testJavaProject/src/ast/NUMBER.java
  src/test/testJavaProject/src/ast/PRINT.java
  src/test/testJavaProject/src/ast/PROGRAM.java
  src/test/testJavaProject/src/ast/SET.java
  src/test/testJavaProject/src/ast/STATEMENT.java
  src/test/testJavaProject/src/libs/Node.java
  src/test/testJavaProject/src/libs/Tokenizer.java
  src/test/testJavaProject/src/ui/Main.java
Labels: enhancement

#79 Setup Github Actions
  .github/workflows/unit-tests.yml
Labels: enhancement

#26 Update README
  README.md
Labels: documentation, help wanted

#70 Update legend
  client/public/index.html
  client/src/assets/fences/stoneFence.png
  client/src/assets/fences/woodenFence.png
  client/src/components/ClassClusters/index.tsx
  client/src/components/ColoredFlag/index.tsx
  client/src/components/IconTooltip/index.tsx
  client/src/components/ImportPanel/index.tsx
  client/src/components/Legend/Legend.css
  client/src/components/Legend/Legend.module.css
  client/src/components/Legend/index.tsx
  client/src/components/TooltipSquare/index.tsx
Labels: bug, enhancement

#77 Add package name to import
  .gitignore
  src/main/java/com/github/algobot76/surabaya/util/StaticAnalysisVisitor.java
  src/test/java/com/github/algobot76/surabaya/util/AnalyzerTests.java
Labels: bug

#81 fix turbulence animation
  client/public/index.html
Labels: bug

#83 add file name to islands
  client/src/components/ClassClusters/index.tsx
  client/src/components/FileName/index.tsx
  client/src/components/Island/index.tsx
  client/src/util/constants.js
Labels: enhancement

#69 JavaArchipelago wrapper class for JavaProject visualization
  README.md
  client/.gitignore
  client/package.json
  client/src/App.js
  client/src/JavaProjectTypes.ts
  client/src/components/ImportPanel/index.tsx
  client/src/components/Island/index.tsx
  client/src/lib/JavaArchipelago.ts
  client/src/util/constants.js
  client/src/util/helpers.js
  client/src/util/helpers.ts
  client/yarn.lock
Labels: enhancement

#87 Fix file name rendering
  client/src/components/Island/index.tsx
Labels: bug

#101 Remove .yarn-integrity
  node_modules/.yarn-integrity
Labels: bug

#97 Added Zooming and adjusted distances between clusters
  client/package.json
  client/src/App.module.css
  client/src/assets/icons/red dotted line.svg
  client/src/assets/icons/white dotted line.svg
  client/src/components/Island/index.tsx
  client/src/components/Legend/index.tsx
  client/src/components/RightSide/index.tsx
  client/src/lib/JavaArchipelago.ts
  client/src/util/constants.js
  client/yarn.lock
Labels: enhancement

#105 Parse implements
  src/main/java/com/github/algobot76/surabaya/util/StaticAnalysisVisitor.java
  src/test/java/com/github/algobot76/surabaya/util/AnalyzerTests.java
  src/test/resources/SampleJavaProjects/simpleImplements.zip
Labels: bug

#107 reorganized the left side a bit
  client/src/components/ImportPanel/index.tsx
  client/src/components/Legend/Legend.module.css
  client/src/components/Legend/index.tsx
Labels: enhancement

#109 hide outer scroll
  client/src/index.css
Labels: enhancement

#108 Display source code in Code Mirror
  client/package.json
  client/src/App.tsx
  client/src/atoms/index.ts
  client/src/components/ClassClusters/index.tsx
  client/src/components/CodeDisplay/CodeDisplay.css
  client/src/components/CodeDisplay/index.tsx
  client/src/components/IconTooltip/index.tsx
  client/src/components/Legend/Legend.module.css
  client/src/components/Legend/index.tsx
  client/src/components/RightSide/index.tsx
  client/yarn.lock
Labels: enhancement

#111 Update README
  README.md
Labels: documentation

#112 set initial scale to 1
  surabaya-client/src/components/Island/index.tsx
  surabaya-client/src/components/IslandGlow/index.tsx
  surabaya-client/src/components/RightSide/index.tsx
  surabaya-client/src/components/TooltipSquare/index.tsx
  surabaya-client/src/util/constants.js
  surabaya-client/src/util/helpers.ts
Labels: enhancement

#113 Update styling
  surabaya-client/src/App.module.css
  surabaya-client/src/components/CodeDisplay/CodeDisplay.css
  surabaya-client/src/components/CodeDisplay/index.tsx
Labels: enhancement

#114 Fix island placement
  surabaya-client/package.json
  surabaya-client/public/index.html
  surabaya-client/src/App.tsx
  surabaya-client/src/components/CodeDisplay/CodeDisplay.css
  surabaya-client/src/components/DependencyArrow/DomesticDependencyArrow.tsx
  surabaya-client/src/components/DependencyArrow/ForeignDependencyArrow.tsx
  surabaya-client/src/components/Island/index.tsx
  surabaya-client/src/components/PackageNameBanner/index.tsx
  surabaya-client/src/components/WelcomeToSurabaya/index.tsx
  surabaya-client/src/lib/JavaArchipelago.ts
  surabaya-client/src/util/constants.js
  surabaya-client/src/util/helpers.ts
Labels: enhancement
